import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';

const publicDocsDir = path.join(process.cwd(), 'public', 'docs');
if (!fs.existsSync(publicDocsDir)) {
  fs.mkdirSync(publicDocsDir, { recursive: true });
}

const docs = [
  {
    filename: 'policy-schedule.pdf',
    title: 'Policy Schedule',
    content: `
PAYMIGO INSURANCE CO.

Policy ID: PK-9928-X
Holder Name: Partner User
Plan Type: Pro Base Plan
Status: ACTIVE

COVERAGE DETAILS
- Maximum Coverage Limit: Rs. 15,000 / month
- Base Premium: Rs. 119 / week
- Auto-Deduct Trigger: Enabled via UPI AutoPay

INSURANCE TRIGGERS
- Rainfall Intensity: > 15mm/hr in targeted zone
- AQI Hazard Level: > 300 PM2.5 threshold
- Minimum Payout Speed: 90 seconds direct to Wallet

Subject to terms of the Paymigo Gig-Worker Protection Act. Keep this schedule safe.
    `
  },
  {
    filename: 'terms-and-conditions.pdf',
    title: 'Terms & Conditions',
    content: `
GENERAL TERMS AND CONDITIONS

1. PARAMETRIC MODEL
This is a parametric insurance policy. Payouts are entirely conditional upon independent verified data from external 
authorities crossing the thresholds described in the Policy Schedule.

2. PROOF OF LOSS
Zero touch methodology. You will NOT be asked for proof of loss, photographs, or agent verifications. Once the 
hyperlocal index is met, the platform triggers automated reconciliation.

3. LOYALTY & CASHBACK
Fuel cashback caps vary by plan (Basic/Pro/Premium) and are credited every Tuesday. Maintaining a continuous 
weekly premium streak awards an increasing multiplier limit to payout values (up to +10%).

4. CANCELLATION
You may pause your premium directly from the "My Policy" dashboard before standard market hours on Mondays. 
Pausing suspends trigger benefits for the week.
    `
  },
  {
    filename: 'trigger-mechanism-guide.pdf',
    title: 'Trigger Mechanism Guide',
    content: `
TRIGGER MECHANISM AND DATA SCIENCE GUIDE

Grid Precision: 500m Resolution
AI Models: XGBoost Event Probability Matrix

How Paymigo Knows When to Pay You:

1. INGESTION
We actively stream data via 12+ highly redundant APIs connected directly to the IMD, Skymet, and local municipal 
flooding IoT sensors.

2. THE "DISRUPTION" CALCULATION
Instead of city-wide generalized data, we map your active ping location. If extreme weather metrics trigger in 
your mapped localized grid, the payout logic initiates, regardless of the rest of the city.

3. SPEED & SETTLEMENT
If the trigger fires, payouts are routed autonomously via RazorpayX Escrow to your designated UPI. Minimum wait: 
90 seconds based on systemic routing.
    `
  }
];

for (const doc of docs) {
  const file = path.join(publicDocsDir, doc.filename);
  const pdf = new PDFDocument({ margin: 50 });
  
  pdf.pipe(fs.createWriteStream(file));
  
  // Header
  pdf.font('Helvetica-Bold').fontSize(22).text(doc.title, { align: 'center' });
  pdf.moveDown(2);
  
  // Content
  pdf.font('Helvetica').fontSize(12).text(doc.content, { align: 'left', lineGap: 6 });
  
  // Footer
  pdf.moveDown(4);
  pdf.font('Helvetica-Oblique').fontSize(10).fillColor('gray').text('Generated by Paymigo Automated Underwriting System', { align: 'center' });
  
  pdf.end();
  console.log('Generated PDF:', doc.filename);
}
